name: Run CppUTest and Release

on:
  push:
    branches:
      - "**"  # Trigger tests on any branch push
    tags:
      - "v*.*.*"  # Trigger release on tag push


env:
  APP_NAME: my_executable

permissions:
  contents: write

jobs:
  docker-unit-tests:
    runs-on: ubuntu-latest
    name: Build and run unit tests with docker image
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t unit-tests-image -f Dockerfile .

      - name: Run image
        run: docker run --rm unit-tests-image

  release:
    needs: docker-unit-tests
    runs-on: ubuntu-latest
    name: Create a release if CppUTests passed
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      
      - name: Build docker image
        run: docker build -t release-image -f Dockerfile .
      
      - name: Run image
        run: docker run --name release-container release-image

      - name: copy the elf file from the docker to the github dir
        run: docker cp release-container:/${APP_NAME}.elf ./${APP_NAME}.elf

      - name: put app name into env of gihub env
        run: echo "app_name=$APP_NAME" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.app_name }}.elf
          body_path: CHANGELOG.md
