name: Unit Tests


on: [push]

jobs:
  docker-unit-tests:
    runs-on: ubuntu-latest
    name: Build and run unit tests with docker image
    steps:
      -name: check out this repo
       uese: actions/checkout@v3

      -name: Build docker image
       run: docker build -t unit-tests-image -f Dockerfile .

      -name: Run image
       run: docker run --rm unit-tests-image
